### ISSUE TITLE
Test fail on Python 3.5

### ISSUE THREAD

**Issue by toddrme2178** [lincolnloop/python-qrcode#93] opened 2016-01-28 09:53 UTC
The unit tests are failing on Python 3.5 with the following message when pyimaging is not installed:

```Python
======================================================================
ERROR: pure (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: pure
Traceback (most recent call last):
  File "C:\User_Program_Files\Anaconda3\lib\unittest\loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "C:\Users\username\Downloads\qrcode-5.2.2.tar\dist\qrcode-5.2.2\qrcode\image\pure.py", line 1, in <module>
    from pymaging import Image
ImportError: No module named 'pymaging'


======================================================================
ERROR: pure (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: pure
Traceback (most recent call last):
  File "C:\User_Program_Files\Anaconda3\lib\unittest\loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "C:\Users\username\Downloads\qrcode-5.2.2.tar\dist\qrcode-5.2.2\qrcode\image\pure.py", line 1, in <module>
    from pymaging import Image
ImportError: No module named 'pymaging'
```

The tests work fine on all other versions of Python I have tested, but they fail identically on Python 3.5 on two different systems (openSUSE Linux and Anaconda for Windows).

**Comment by SmileyChris** [comment] 2016-01-28 20:09
It begs the question as to why is python 3.5 trying to load the otherwise unreferenced `pure` module as a test module...

**Comment by ekevoo** [comment] 2016-03-01 04:57
I'm using 3.5.1 on OS X El Capitan and I cannot reproduce.

**Comment by SmileyChris** [comment] 2016-03-01 08:59
I'm guessing this is something weird with anaconda. Until further information is provided, I'm going to close this issue.

**Closed by SmileyChris** 2016-03-01 08:59 UTC
